# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:            # Required
        # Examples:
        in_memory:
            memory:
                users:
                    gabi:
                        password:           1234
                        roles:              [ROLE_USER, ROLE_ADMIN]
        token_user:
            id: gabi_u_jobeet.token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_area:
            pattern: ^/api/v1/
            stateless: true
            simple_preauth:
                authenticator: gabi_u_jobeet.token_authenticator
            provider: token_user

        secured_area:
            pattern: ^/
            anonymous: ~
            provider: in_memory
            logout:
                path: /logout
                target: /
            form_login:
                login_path: /login
                username_parameter: form[username]
                password_parameter: form[password]
                check_path: /login_check
                default_target_path: gabi_u_jobeet_homepage

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }