<?php

namespace GabiU\JobeetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends EntityRepository
{
    public function activateAffiliate(Affiliate $affiliate)
    {
        $affiliate->setIsActive(true);
        $this->getEntityManager()->persist($affiliate);
        $this->getEntityManager()->flush();
    }
}
