<?php

namespace GabiU\JobeetBundle\Entity;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;
use GabiU\JobeetBundle\Utils\Jobeet;
use GabiU\JobeetBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getWithJobs($categoryId = null, $number = null)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c,j')
            ->leftJoin('c.jobs','j')
            ->where('j.expiresAt > :date')
            ->andWhere('j.isActivated = :activated')
        ;

        if ($categoryId)
        {
            $query->andWhere('c.id = :id');
            $query->setParameter('id', $categoryId);
        }

        if ($number)
        {
            $query->setMaxResults($number);
        }

        $query->setParameter("date", Jobeet::getCurrentDate());
        $query->setParameter("activated", true);

        return $query->getQuery()->getResult();
    }

    /**
     * @param $slug
     *
     * @return null|Category
     */
    public function findOneBySlug($slug)
    {
        return $this->findOneBy(array("slug" => $slug));
    }
}
