GabiU\JobeetBundle\Entity\Affiliate:
    type: entity
    table: affiliates
    repositoryClass: GabiU\JobeetBundle\Entity\AffiliateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        url:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        token:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
            nullable: false
            default: false
        createdAt:
            type: datetime
            column: created_at
    manyToMany:
        categories:
            targetEntity: Category
            inversedBy: affiliates
            joinTable:
                name: category_affiliate
                joinColumns:
                    affiliate_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setTokenValue ]
