GabiU\JobeetBundle\Entity\Category:
    type: entity
    table: categories
    repositoryClass: GabiU\JobeetBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: Category
    manyToMany:
        affiliates:
            targetEntity: Affiliate
            mappedBy: categories
    lifecycleCallbacks: {  }
