GabiU\JobeetBundle\Entity\Category:
    type: entity
    table: categories
    repositoryClass: GabiU\JobeetBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        jobs:
            targetEntity: GabiU\JobeetBundle\Entity\Job
            mappedBy: category
    manyToMany:
        affiliates:
            targetEntity: GabiU\JobeetBundle\Entity\Affiliate
            mappedBy: categories
    lifecycleCallbacks:
        prePersist: [ setSlugValue ]
        preUpdate: [ setSlugValue ]