gabi_u_jobeet_get_job:
    type: rest
    prefix: /v1
    resource: @GabiUJobeetBundle/Controller/ApiController.php
    name_prefix: api_1_

gabi_u_jobeet_get_json_job:
    path: /v1/{token}/{id}
    defaults: { _controller: GabiUJobeetBundle:Api:getJobJson }