job_show:
    path:     /{company}/{location}/{id}/{position}/
    defaults: { _controller: "GabiUJobeetBundle:Job:show" }
    requirements:
        id: \d+

job_preview:
    path:     /{token}/
    defaults: { _controller: "GabiUJobeetBundle:Job:preview" }
    requirements:
        id: \w+
    methods: [GET, POST, PUT]

job_new:
    path:     /new
    defaults: { _controller: "GabiUJobeetBundle:Job:new" }

job_create:
    path:     /create
    defaults: { _controller: "GabiUJobeetBundle:Job:create" }
    methods:  POST

job_edit:
    path:     /{token}/edit
    defaults: { _controller: "GabiUJobeetBundle:Job:edit" }

job_update:
    path:     /{token}/update
    defaults: { _controller: "GabiUJobeetBundle:Job:update" }
    methods:  [POST, PUT]

job_delete:
    path:     /{token}/delete
    defaults: { _controller: "GabiUJobeetBundle:Job:delete" }
    methods:  [POST, DELETE]
