gabi_u_jobeet_homepage:
    path:     /
    defaults: { _controller: "GabiUJobeetBundle:Job:index" }

gabi_u_jobeet_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: GabiUJobeetBundle:Category:show, page: 1 }

gabi_u_jobeet_all_feed:
    path:     /feed/{page}
    defaults: { _controller: GabiUJobeetBundle:Feed:index, page: 1, _format: atom }
    requirements: { _format: atom, page: "\d+" }

gabi_u_jobeet_category_feed:
    path:     /feed/category/{slug}/{page}
    defaults: { _controller: GabiUJobeetBundle:Feed:category, page: 1, _format: atom }
    requirements: { _format: atom, page: "\d+" }
    methods: GET

login:
    path: /login
    defaults: { _controller: "GabiUJobeetBundle:Admin:login" }

login_check:
    path: /login_check

logout:
    path: /logout

gabi_u_jobeet_job:
    resource: "@GabiUJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

easy_admin_bundle:
    resource: "@GabiUJobeetBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

gabi_u_jobeet_api:
    type: rest
    prefix: /api
    resource: "@GabiUJobeetBundle/Resources/config/routing/api.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

affiliate_new:
    path:     /affiliate/new
    defaults: { _controller: GabiUJobeetBundle:Affiliate:new }

affiliate_create:
    path:     /create
    defaults: { _controller: GabiUJobeetBundle:Affiliate:create }

affiliate_wait:
    path:     /wait
    defaults: { _controller: GabiUJobeetBundle:Affiliate:wait }

search:
    path:     /search/{page}
    defaults: { _controller: GabiUJobeetBundle:Search:search, page: 1}

#type_ahead:
#    path:     /typeAhead
#    defaults: { _controller: GabiUJobeetBundle:Search:typeAhead, _format: json }
