gabi_u_jobeet_homepage:
    path:     /
    defaults: { _controller: "GabiUJobeetBundle:Job:index" }

login_check:
    path: /login_check

login:
    path: /login
    defaults: { _controller: "GabiUJobeetBundle:Admin:login" }

logout:
    path: /logout

gabi_u_jobeet_job:
    resource: "@GabiUJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

gabi_u_jobeet_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: GabiUJobeetBundle:Category:show, page: 1 }

easy_admin_bundle:
    resource: "@GabiUJobeetBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin