gabi_u_jobeet_job:
    resource: "@GabiUJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

gabi_u_jobeet_homepage:
    path:     /hello/{name}
    defaults: { _controller: GabiUJobeetBundle:Default:index }
