gabi_u_jobeet_homepage:
    path:     /
    defaults: { _controller: "GabiUJobeetBundle:Job:index" }

gabi_u_jobeet_job:
    resource: "@GabiUJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

gabi_u_jobeet_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: GabiUJobeetBundle:Category:show, page: 1 }
