imports:
    - { resource: parameters.yml }

services:
    gabi_u_jobeet.page.handler:
        class: %gabiu.jobeet.job.handler.class%
        arguments: [@doctrine.orm.entity_manager, %gabiu.jobeet.job.class% ]

    gabi_u_jobeet.affiliate_emailer_listener:
        class: GabiU\JobeetBundle\EventListener\AffiliateEmailerListener
        arguments:
            - @logger
            - @gabi_u_jobeet.affiliate_emailer_sender
        tags:
            - { name: doctrine.event_listener, event: postUpdate }

    gabi_u_jobeet.affiliate_emailer_sender:
        class: GabiU\JobeetBundle\Mailer\AffiliateMailer
        arguments:
            - @@jobeet_template
            - @mailer
            - %affiliate_mailer_template%

    jobeet_template:
        class: GabiU\JobeetBundle\Mailer\TemplateRender
        arguments: [@service_container]

    gabi_u_jobeet.token_user_provider:
        class: GabiU\JobeetBundle\Security\TokenUserProvider
        arguments:
            - @doctrine.orm.entity_manager

    gabi_u_jobeet.token_authenticator:
        class: GabiU\JobeetBundle\Security\TokenAuthenticator
        public: false

#    gabi_u_jobeet.example:
#        class: GabiU\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
