imports:
    - { resource: parameters.yml }

services:
    gabi_u_jobeet.affiliate_emailer_listener:
        class: GabiU\JobeetBundle\EventListener\AffiliateEmailerListener
        arguments:
            - @logger
            - @gabi_u_jobeet.affiliate_emailer_sender
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
    gabi_u_jobeet.affiliate_emailer_sender:
        class: GabiU\JobeetBundle\Mailer\AffiliateMailer
        arguments:
            - @templating
            - @mailer
            - %affiliate_mailer_template%
#    gabi_u_jobeet.example:
#        class: GabiU\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
