imports:
    - { resource: parameters.yml }
    - { resource: events.yml }

services:
    gabi_u_jobeet.job.type:
        class: GabiU\JobeetBundle\Entity\Job
        factory_class: GabiU\JobeetBundle\Entity\Job
        factory_method: getTypes

    gabi_u_jobeet.page.handler:
        class: %gabiu.jobeet.job.handler.class%
        arguments: [@doctrine.orm.entity_manager, %gabiu.jobeet.job.class% ]

    gabi_u_jobeet.affiliate_emailer_sender:
        class: GabiU\JobeetBundle\Mailer\AffiliateMailer
        arguments:
            - @jobeet_template
            - @mailer
            - %affiliate_mailer_template%

    jobeet_template:
        class: GabiU\JobeetBundle\Mailer\TemplateRender
        arguments: [@service_container]

    gabi_u_jobeet.token_user_provider:
        class: GabiU\JobeetBundle\Security\TokenUserProvider
        arguments:
            - @doctrine.orm.entity_manager

    gabi_u_jobeet.token_authenticator:
        class: GabiU\JobeetBundle\Security\TokenAuthenticator
        public: false

    gabi_u_jobeet.searchFormBuilder:
        class: GabiU\JobeetBundle\Form\SearchForm
        arguments:
            - @form.factory
            - @router

    gabi_u_jobeet.webmailGuesser:
        class: GabiU\JobeetBundle\Utils\EmailProviderGuesser

#    gabi_u_jobeet.example:
#        class: GabiU\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
