imports:
    - { resource: parameters.yml }
    - { resource: events.yml }

services:
    gabi_u_jobeet.page.handler:
        class: %gabiu.jobeet.job.handler.class%
        arguments: [@doctrine.orm.entity_manager, %gabiu.jobeet.job.class% ]

    gabi_u_jobeet.token_user_provider:
        class: GabiU\JobeetBundle\Security\TokenUserProvider
        arguments:
            - @doctrine.orm.entity_manager

    gabi_u_jobeet.token_authenticator:
        class: GabiU\JobeetBundle\Security\TokenAuthenticator
        public: false

    gabi_u_jobeet.searchFormBuilder:
        class: GabiU\JobeetBundle\Form\SearchForm
        arguments:
            - @form.factory
            - @router

#    gabi_u_jobeet.example:
#        class: GabiU\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
