imports:
    - { resource: parameters.yml }

services:
    gabi_u_jobeet.page.handler:
        class: %gabiu.jobeet.job.handler.class%
        arguments: [@doctrine.orm.entity_manager, %gabiu.jobeet.job.class% ]